name: Trigger specs
on:
  workflow_dispatch:
    inputs:
      specs:
        description: Comma-separates spec filenames without spaces
        required: true
jobs:
  specs:
    runs-on: ubuntu-20.04
    steps:
      - name: Print specs 🖨️
        env:
          SPECS: ${{ toJson(github.event.inputs.specs) }}
        run: echo "$SPECS"

      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run selected specs 🏃
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:8888'
          spec: '${{ github.event.inputs.specs }}'
          record: true
          tag: Trigger specs
          group: Selected specs
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
